version: '3.8'

services:
  inf:
    image: ubuntu
    container_name: infra-only 
    networks:
      - net

networks:
# Network for all Services (across Projects)
  net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.100.0/24
        gateway: 192.168.100.1