version: '3.8'

services:
  traefik:
    image: traefik
    container_name: traefik
    command: 
     - "--api.insecure" 
     - "--providers.docker"
#     - "--providers.docker.exposedbydefault=false"
#     - "--entrypoints.web.address=:80"     
    ports:
     - 80:80
     - 8080:8080
    volumes:
     - traefik:/traefik
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - net  
  
  inf:
    image: nginx
    container_name: infra-only
    ports:
     - 8181:80
    labels:
#      - "traefik.enable=true"
      - "traefik.http.routers.inf.rule=Host('inf.local')"
#      - "traefik.http.routers.inf.entrypoints=web"
    networks:
      - net  
    depends_on:
     - traefik

volumes:
  traefik:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=192.168.1.11,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4"
      device: ":/volume1/docker/traefik"  

networks:
# Network for all Services (across Projects)
  net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.100.0/24
        gateway: 192.168.100.1