version: '3.8'

services:
  inf:
    image: ubuntu
    container_name: infra-only 
    networks:
      - net

  traefik:
    image: traefik
    container_name: traefik
    command: --api.insecure=true --providers.docker-true
    ports:
     - 80:80
     - 8080:8080
    volumes:
     - traefik:/var/run/docker.sock
    networks:
     - net  

volumes:
  traefik:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=192.168.1.11,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4"
      device: ":/volume1/docker/traefik"  

networks:
# Network for all Services (across Projects)
  net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.100.0/24
        gateway: 192.168.100.1